# Generated by Django 5.1.4 on 2025-03-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
    ]
