# Generated by Django 5.1.4 on 2025-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_province_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
