# Generated by Django 5.1.4 on 2025-03-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_province_code_regency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regency',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.province'),
        ),
    ]
