# Generated by Django 5.1.4 on 2025-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_regency_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='regency',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
