# Generated by Django 5.1.4 on 2025-03-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_subdistrict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdistrict',
            options={'ordering': ['name']},
        ),
    ]
