# Generated by Django 5.1.4 on 2025-03-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_subdistrict_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('meta', models.JSONField(default=dict)),
                ('subdisctrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subdistrict')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
