# Generated by Django 5.1.4 on 2025-03-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='subdisctrict',
            new_name='subdistrict',
        ),
    ]
