# Generated by Django 5.1.7 on 2025-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_rename_subdisctrict_village_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
