# Generated by Django 5.1.7 on 2025-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_studyprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=9)),
            ],
            options={
                'ordering': ['period'],
            },
        ),
    ]
