# Generated by Django 5.1.7 on 2025-03-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_registrationperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
