# Generated by Django 5.1.7 on 2025-03-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['job'],
            },
        ),
    ]
