# Generated by Django 5.1.7 on 2025-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['income'],
            },
        ),
    ]
