# Generated by Django 5.1.7 on 2025-04-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['amount']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='name',
        ),
    ]
